### ISSUE TITLE
Fig 4.3 (b) showing Runge's effect

### ISSUE THREAD

**Issue by pratyush1611** [tudelft3d/terrainbook#16]
The text says that Runge's Phenomenon is observed when the polynomial overshoots at samples. In the figure, the polynomial is supposed to be $C^2$ i.e. continuous and smooth so that it can be differentiated at all points, however, at around x=5, there is a sharp change in the polynomial curve, where it won't be differentiable and thus not $C^2$ (since the limit of a function doesn't exist at points where the slope changes abruptly)

**Comment by hugoledoux** [comment]
you're totally right, cheers. Fixed.
