### ISSUE TITLE
(Questions/typos not sure) for Chapter 12, page 126

### ISSUE THREAD

**Issue by SEUZFY** [tudelft3d/terrainbook#32]
![image](https://user-images.githubusercontent.com/72781910/146785623-3fa04b96-a0c9-4d6f-a5bf-6ed7d1772758.png)

why the scale turning to 0.4 from 0.5 means "more tension" rather than "less tension"? From 0.5 to 0.4, the size of the display vector representing internal force becomes smaller. According to the previous description, it should be more loose. Why is it more “tension”？

**Comment by hugoledoux** [comment]
What I wrote is correct. If using 0.4 instead of 0.5 the movement is smaller, than this mean that the tension in the cloth is higher, it is more rigid and thus less movement in the cloth is allowed.

**Comment by SEUZFY** [comment]
> What I wrote is correct. If using 0.4 instead of 0.5 the movement is smaller, than this mean that the tension in the cloth is higher, it is more rigid and thus less movement in the cloth is allowed.

Thanks for the clear explanation!
