### ISSUE TITLE
A small typo thing

### ISSUE THREAD

**Issue by MCHU-1999** [tudelft3d/terrainbook#55]
In page 89, section "Computing for TINs":
"If there are 2 segments,... , it will be perpendicular in the direction **or** lower elevations".
I wonder should it be "or" or "of"?
<img width="666" alt="image" src="https://github.com/user-attachments/assets/f9bb9c6a-5ccc-4fd6-8ed5-6ac90e45248e">

Also, in chapter 8, page 90, section "Roughness & ruggedness":
"A terrain with a high roughness will have small local deviations". I think high roughness indicates large local deviations instead of small, please correct me if I'm wrong.
<img width="559" alt="image" src="https://github.com/user-attachments/assets/2c7a9c91-b018-4f02-936d-1f167b6259e7">

**Comment by hugoledoux** [comment]
first error: thanks fixed.

second error: small local deviations I mean that the bumps are small but very frequent, like the orange profile in Fig8.7

**Comment by MCHU-1999** [comment]
got it, thx!
