### ISSUE TITLE
Section 5.1: defintion of continuous is not clear

### ISSUE THREAD

**Issue by ZokszY** [tudelft3d/terrainbook#57]
In section 5.1, continuous is defined as: "a single and unique value must be obtained at each location. This is called a $C^0$ interpolant in mathematics (see Figure 5.2)"

This definition is a bit unclear to me, because from the figure 5.2 that is mentioned and from the usual definition of continuous, continuous should also mean that there should be no discontinuity in the sense of no vertical break in the curve, which is not mentioned here. But I don't really know how to quickly and precisely explain this without using maths, so I can just pinpoint the problem.

**Comment by hugoledoux** [comment]
okay, my solution would be to add a sub-figure to fig5.2 with a curve that is with different horizontal lines (and thus not continuous).

Would that clarify it enough?

**Comment by ZokszY** [comment]
Yes I think that this would be enough.
